import type { Metadata } from "next"
import { Inter as FontSans } from "next/font/google"
import "./globals.css"
import { cn } from "@/lib/utils"
import { Providers } from "./Providers"
import { Header } from "@/components/organisms/Header"
import { Sidebar } from "@/components/organisms/sidebar"

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <body className={cn("min-h-screen bg-background font-sans antialiased", fontSans.variable)}>
          <Header />
          <div className="flex">
            <Sidebar className="h-full max-w-80 border-r-[1px]" />
            <main className="py-7 px-6 w-full">
              {children}
            </main>
          </div>
        </body>
      </Providers>
    </html>
  )
}
